name: next_set
description: "A new Flutter project."
publish_to: "none"
version: 1.0.2+12

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  wakelock_plus: ^1.4.0
  url_launcher: ^6.3.1
  audioplayers: ^6.1.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_foreground_task: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "next_set_logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "next_set_logo.png"
  web:
    generate: true
    image_path: "next_set_logo.png"
  windows:
    generate: true
    image_path: "next_set_logo.png"
  macos:
    generate: true
    image_path: "next_set_logo.png"

flutter_native_splash:
  color: "#000000"
  image: "next_set_logo.png"
  android_12:
    color: "#000000"
    image: "next_set_logo.png"
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - assets/bell_sound.mp3
    - assets/notification_sound.mp3
